### ISSUE TITLE
batman: support mouse wheel scrolling

### ISSUE THREAD

**Issue by nazrhyn** [eth-p/bat-extras#11]
Hey, I'm back with hopefully a quick one.

When using my default configured `man`, I can scroll with the keyboard or the mouse wheel. Is it possible or easy to have the mouse wheel work for `batman` as well?

Thanks!

**Comment by eth-p** [comment]
By default, all the scripts try and emulate bat's regular pager behavior.

Unfortunately, that also means passing `--no-init` to `less`, which prevents it from using the alternate screen mode. Scroll wheel events are only sent inside the alternate screen mode, which is why this doesn't work as expected.

If you don't mind setting an environment variable in your bash profile file, there's a couple workarounds you can use:

**If you have less 530 or newer:**  
This will use the pager if there's mode than one screen of text: `export BAT_PAGER='less -RF'`

**If you have an older version of less:**
This will always use the pager: `export BAT_PAGER='less -R'`

If you don't mind waiting for #10, you would be able to set `MANPAGER` instead of `BAT_PAGER` for the above options, which would only affect `batman` and not regular `bat`.

**Comment by nazrhyn** [comment]
Thanks for the quick response! Definitely don't mind waiting. I did read that other issue, but didn't quite realize how the two questions would be related.

Thanks for your work on these scripts; they've definitely improved my command line QOL. Good luck with classes!

**Comment by eth-p** [comment]
Support for `MANPAGER` was added in 5cbbbb6. Once you update, you should be able to set `export MANPAGER='less -R'` in your .bash_profile file to bring back the original `man` paging behaviour.

**Comment by nazrhyn** [comment]
Mouse wheel scrolling confirmed! :tada:

**Comment by nazrhyn** [comment]
I saw your 🎉; I figure this is good? I'll close it to clean up your issues 🤓.
