### ISSUE TITLE
Pager functionality breaks if PAGER contains arguments

### ISSUE THREAD

**Issue by lilyball** [eth-p/bat-extras#24]
The `PAGER` env var is usually treated like a shell command, so it can be written like `less -R`. Unfortunately, bat-extras treats it like an executable, so `PAGER='less -R'` breaks. For `batgrep` and `batwatch` it produces an error message, and for `batman` it just disables paging (because `bat` handles garbage pagers by disabling paging, and the script is passing `BAT_PAGER='less\ -R'` to it). `prettybat` is the only one that works, because it doesn't touch the pager at all and falls back to `bat`'s built-in behavior.

Incidentally, I have no idea why `batman` constructs a `BAT_PAGER` env var instead of just using `bat`'s built-in behavior.

**Comment by lilyball** [comment]
FWIW this affects NixOS by default as that OS defaults the `PAGER` var to `less -R`.

**Comment by eth-p** [comment]
I took another look at https://github.com/sharkdp/bat/blob/master/src/output.rs, and I did have the behavior implemented incorrectly. It should be fixed in the latest commit.

> Incidentally, I have no idea why batman constructs a BAT_PAGER env var instead of just using bat's built-in behavior.

That was to take advantage of the script's option parsing hooks for `--paging=[never|always]` and `--pager='pager --args'`. I might just replace that by simply copying those arguments, though.

**Comment by eth-p** [comment]
If you can confirm this is fixed, I plan on releasing a new version with the tag `v2020.04.30`.

Since the last release, I changed the versioning scheme to not combine the date into a single number, but as a YYYY.MM.DD version tuple. This shouldn't be a problem for https://github.com/NixOS/nixpkgs/pull/85982, since `bat-extras` doesn't exist yet, right?

**Comment by lilyball** [comment]
I can confirm that `PAGER='less -R' batgrep …` now pages instead of producing an error. I left some comments on 9f983891fd4e7da9933616a0e73ea8271a67b535 though.

**Comment by lilyball** [comment]
I suppose I can go ahead and close this since `PAGER='less -R'` works in my tests.
