### ISSUE TITLE
Allow batgrep to page results

### ISSUE THREAD

**Issue by filipekiss** [eth-p/bat-extras#5]
`batgrep` is great, but I miss the option to page the results. I usually go back to using `rg -p foo | bat` but it's not ideal since I can't use syntax highlight. 

Maybe we could pass-trough the `--paging` option to bat?

Great tools, btw!

**Comment by eth-p** [comment]
Due to the way that some things are currently implemented in `bat`, `batgrep` actually requires multiple invocations of `bat`. I'm hoping to eventually change this with a generalized approach to per-file parameters (e.g. https://github.com/sharkdp/bat/issues/654) that I'm currently toying with in a local branch.

In the meantime, I made the choice to explicitly disable bat's pager in batgrep to prevent 20 instances of less from being opened. I'll add a way to pipe `batgrep` to the `BAT_PAGER` or `PAGER` environment variables.

**Comment by eth-p** [comment]
This should be fixed in https://github.com/eth-p/bat-extras/commit/e71de135e6dbd18dd73ba1bd4e493e9c83cf5813.

I tried to make it behave similarly to `bat`:

- If there's `BAT_PAGER="less"`, it will use `less`.
- If there's `PAGER="vimpager --some-argument"`, it will use `vimpager --some-argument`.
- If there's `PAGER="less"`, it will use `less -R`.
- If it detects a non-tty output, it will disable the pager unless it was explicitly set with `--pager=less -R` or something similar.

Tell me if you find any issues with the implementation.

**Comment by filipekiss** [comment]
This is exactly what I needed. Thank you, Ethan! For both the code and for the fast reply! Cheers!

**Comment by eth-p** [comment]
Closed since it's been nearly 30 days without any additional issues.

**Comment by minhtrancccp** [comment]
i specified another pager in `bat` config file as `--pager=ov` but `batgrep` doesn't repect that, even though `batman` does. do i have to configure the `PAGER` env var as well?
