### ISSUE TITLE
batpipe: `./build.sh --compress` causes wrong `LESSOPEN`

### ISSUE THREAD

**Issue by xecua** [eth-p/bat-extras#82]
When I build scripts with `--compress` option and run `batpipe`, its output becomes 
```bash
# batpipe, a bat-based preprocessor for less and bat.
# Version: 2022.07.27
# Homepage: https://github.com/eth-p/bat-extras
# Copyright (C) 2019-2021 eth-p | MIT License
#
# To use batpipe, eval the output of this command in your shell init script.
LESSOPEN="|/tmp/bat-extras/ %s";
export LESSOPEN;
unset LESSCLOSE;

# The following will enable colors when using batpipe with less:
LESS="$LESS -R";
BATPIPE="color";
export LESS;
export BATPIPE;
```
where `LESSOPEN` should be `/tmp/bat-extras/bin/batpipe`.
`/tmp/bat-extras` part changes according to the path where I run `batpipe`.

(I assume that this is caused by evaluating `SELF` variable defined with `BASH_SOURCE` in `bash -c` context of compressed `batpipe` script, and that this may be fixed by using `$0` as fallback for `BASH_SOURCE`).

**Comment by eth-p** [comment]
Haha, oh man. I didn't expect to encounter an issue like this, but I suppose that's what happens when I use obtuse methods to compress bash scripts while keeping them self-contained 😅

Fixed in a7abf437b59f28af5fd052704b725aba9afe2499. In a more ideal world, `bash` would've let me set `BASH_SOURCE` from the wrapper script, but it doesn't like it when you try and set it manually. I used your suggestion to fall back on `$0`, thanks :)
